# Generated by Django 3.1 on 2020-09-09 12:01

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500, verbose_name='Libelle')),
            ],
            options={
                'verbose_name': 'catedgorie',
                'verbose_name_plural': 'catedgories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('entreprise', models.CharField(max_length=500, verbose_name='Entreprise')),
                ('commune', models.CharField(max_length=500, verbose_name='Commune')),
                ('quartier', models.CharField(max_length=500, verbose_name='Quartier')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('etat', models.BooleanField(verbose_name='Etat')),
                ('info_livraison', models.TextField(verbose_name='Informations de livraison')),
                ('total', models.IntegerField(verbose_name='Total')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500, verbose_name='Libelle')),
                ('image', models.ImageField(upload_to='', verbose_name='Illustration')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('prix_unitaire', models.FloatField(verbose_name='Prix Unitaire')),
                ('quantite_stock', models.IntegerField(verbose_name='Quantite en stock')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AkunaApp.categorie')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AkunaApp.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AkunaApp.produit')),
            ],
            options={
                'verbose_name': 'liste',
                'verbose_name_plural': 'listes',
            },
        ),
    ]
