# Generated by Django 3.1.1 on 2020-12-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AkunaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'managed': True, 'verbose_name': 'categorie', 'verbose_name_plural': 'categories'},
        ),
    ]
