# Generated by Django 3.1.1 on 2020-12-05 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AkunaApp', '0003_auto_20201205_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date demodification'),
        ),
        migrations.AddField(
            model_name='produit',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
    ]
