# Generated by Django 3.1.1 on 2020-12-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AkunaApp', '0004_auto_20201205_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to='akuna_produits', verbose_name='Illustration'),
        ),
    ]
